// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<{[key: string]: any}>;

export function ClearHistory():Promise<void>;

export function Connect():Promise<void>;

export function Disconnect():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetDefaultPrinterName():Promise<string>;

export function GetHistory():Promise<Array<{[key: string]: any}>>;

export function GetPrinterStatusInfo():Promise<{[key: string]: any}>;

export function GetPrinters():Promise<Array<string>>;

export function GetStatus():Promise<{[key: string]: any}>;

export function GetTicketPreview(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;

export function IsAutoStartEnabled():Promise<boolean>;

export function IsConfigured():Promise<boolean>;

export function OpenAppFolder():Promise<void>;

export function OpenTicketsFolder():Promise<void>;

export function QuitApp():Promise<void>;

export function Reconnect():Promise<void>;

export function ReprintJob(arg1:string):Promise<void>;

export function ReprintLast():Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function TestPrint():Promise<void>;

export function ValidateKey(arg1:string):Promise<string>;
