// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDefaultPrinterName() {
  return window['go']['main']['App']['GetDefaultPrinterName']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetPrinterStatusInfo() {
  return window['go']['main']['App']['GetPrinterStatusInfo']();
}

export function GetPrinters() {
  return window['go']['main']['App']['GetPrinters']();
}

export function GetPrintersConfig() {
  return window['go']['main']['App']['GetPrintersConfig']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTicketPreview(arg1) {
  return window['go']['main']['App']['GetTicketPreview'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsAutoStartEnabled() {
  return window['go']['main']['App']['IsAutoStartEnabled']();
}

export function IsConfigured() {
  return window['go']['main']['App']['IsConfigured']();
}

export function OpenAppFolder() {
  return window['go']['main']['App']['OpenAppFolder']();
}

export function OpenTicketsFolder() {
  return window['go']['main']['App']['OpenTicketsFolder']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function Reconnect() {
  return window['go']['main']['App']['Reconnect']();
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function RemovePrinter(arg1) {
  return window['go']['main']['App']['RemovePrinter'](arg1);
}

export function ReprintJob(arg1) {
  return window['go']['main']['App']['ReprintJob'](arg1);
}

export function ReprintLast() {
  return window['go']['main']['App']['ReprintLast']();
}

export function SaveAccount(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveAccount'](arg1, arg2, arg3, arg4, arg5);
}

export function SavePrinter(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SavePrinter'](arg1, arg2, arg3, arg4, arg5);
}

export function SetAPIUrl(arg1) {
  return window['go']['main']['App']['SetAPIUrl'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function TestPrint(arg1) {
  return window['go']['main']['App']['TestPrint'](arg1);
}

export function ValidateKey(arg1) {
  return window['go']['main']['App']['ValidateKey'](arg1);
}
